name: chapter8
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  provider: ^6.0.0
  flutter_colorpicker: ^1.0.3
  intl: ^0.18.0
  uuid: ^3.0.4
  smooth_page_indicator: ^1.0.0+2
  webview_flutter: ^4.0.5
  url_launcher: ^6.0.10
  shared_preferences: ^2.0.7
  webview_flutter_android: ^3.3.1




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/food_pics/
    - assets/magazine_pics/
    - assets/sample_data/
    - assets/profile_pics/
    - assets/fooderlich_assets/

